
// Generated by build tool, do not edit
using System;
using System.Reflection;
[assembly: AssemblyCopyright("Copyright © 2019-2024 Topten Software. All Rights Reserved")]
[assembly: AssemblyVersion("0.4.168")]
[assembly: AssemblyFileVersion("0.4.168")]
[assembly: AssemblyCompany("Topten Software")]
[assembly: AssemblyProduct("Topten.VL.RichTextKit")]

static class BuildInfo
{
	public static DateTime Date = new DateTime(2024, 10, 9, 114, 30, 00, DateTimeKind.Utc);
}
	